### compilation stage
FROM node:16 AS build

RUN mkdir /build
WORKDIR /build

COPY package.json .
RUN npm install

COPY . .
RUN npm run build

#### NGINX FOR Single Page Application ####
FROM milung/nginx-spa

COPY --from=build /build/dist /app

EXPOSE 80

CMD ["nginx"]
