version: '3.5'

services:
  details:
    build:
      dockerfile: Dockerfile.go
      context: .
    depends_on:
      - postgres
    volumes:
      - ./details/:/opt/app/api
    network_mode: "host"
  filter:
    build:
      dockerfile: Dockerfile.go
      context: .
    depends_on:
      - postgres
    volumes:
      - ./filter/:/opt/app/api
    network_mode: "host"
  products:
    build:
      dockerfile: Dockerfile.go
      context: .
    depends_on:
      - postgres
    volumes:
      - ./products/:/opt/app/api
    network_mode: "host"
  searcher:
    build:
      dockerfile: Dockerfile.go
      context: .
    depends_on:
      - postgres
    volumes:
      - ./searcher/:/opt/app/api
    network_mode: "host"

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - ./postgres:/data/postgres
    network_mode: "host"
    restart: unless-stopped

volumes:
    postgres: