version: '3.5'

services:
  details:
    build:
      dockerfile: Dockerfile.go
      context: ./details/
    volumes:
      - ./details/:/opt/app/api
    networks:
      - comnet
  filter:
    build:
      dockerfile: Dockerfile.go
      context: ./filter/
    volumes:
      - ./filter/:/opt/app/api
    networks:
      - comnet
  products:
    build:
      dockerfile: Dockerfile.go
      context: ./products/
    volumes:
      - ./products/:/opt/app/api
    networks:
      - comnet
  searcher:
    build:
      dockerfile: Dockerfile.go
      context: ./searcher/
    volumes:
      - ./searcher/:/opt/app/api
    networks:
      - comnet

  nginx:
    build:
      dockerfile: Dockerfile.nginx
      context: ./nginx/
    networks:
      - comnet
    ports:
      - "8080:80"

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - comnet
    restart: unless-stopped

networks:
  comnet:
    driver: bridge

volumes:
    postgres: