definitions:
  main.GreeterResponse:
    properties:
      message:
        type: string
    type: object
  main.SearchResponse:
    properties:
      message:
        type: string
    type: object
  main.ItemDetail:
    properties:
      message:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample rk-demo server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /v1/greeter:
    get:
      operationId: "1"
      parameters:
      - description: name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.GreeterResponse'
      summary: Greeter
      tags:
      - Hello
  /v1/search:
    get:
      operationId: "2"
      parameters:
        - description: query
          in: query
          name: query
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.SearchResponse'
      summary: Item details
      tags:
        - Details
  /v1/details:
    get:
      operationId: "3"
      parameters:
        - description: item name
          in: query
          name: item
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ItemDetail'
      summary: Search
      tags:
        - Search-Query
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
